### ISSUE TITLE
Discuss visualization approaches

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/SRV-planning#2]
We should try to gather information and discuss about different data/test visualization approaches. Once we have a sense for the platform that we will use for tests, we will need to create an RFC to decide what visualization approach we would like to have.

**Comment by nsevilla** [comment]
See [here](https://docs.google.com/presentation/d/1DY9HiPOATd5HCqal9TPwDWhM-l9kiQyUhdAOvruSvQg/edit#slide=id.p) for the options presented by David Kirkby

**Comment by nsevilla** [comment]
I am going to close this as I think we are currently settling de facto with de descqaweb interface. We can reopen, or open an RFC, if necessary.
