### ISSUE TITLE
Change `VVC_tests_DESC.xlsx` to CSV format

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/SRV-planning#8]
Excel is not a very friendly format. Change it to CSV format will make it easier to read by code. GitHub also display CSV file directly as a table when you browse it (see [example](https://github.com/LSSTDESC/Twinkles/blob/master/data/agn_lens_ids.csv)).

**Comment by nsevilla** [comment]
Solved. Will track CSV from now on.
